# This pipeline tests ThermoSysPro with Dymola on an internal VM (PAM), through
# the internal mirror project ThermoSysPro_mirror of the GitHub repository, so
# that the runner can access the Dymola licence server.
#
# The OpenModelica tests and the documentation (GitHub Pages) run with GitHub
# Actions: see .github/workflows/.
#
# The objectives of the test section are:
#   - Test ThermoSysPro examples within the library
#   - Test extra models (additional gitlab/github projects)
# Options to be developed:
#   - Evaluate changes on some realistic studies (calibration, optimisation, 
# uncertainties propagations...)
#

stages:          # List of stages for jobs, and their order of execution
  - test

test-job-dymola-internal:
  stage: test
  image: nexus.retd.edf.fr:5097/dymola:2025.1Fix
  script:
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_PATH
    - echo $CI_PROJECT_URL
    #- curl --header "PRIVATE-TOKEN:$modelicaTests_token" --url "https://gitlab.pleiade.edf.fr/api/v4/projects/10790/repository/archive" --OUTPUT modelicaTests.tar.gz
    #- tar -xvzf modelicaTests.tar.gz
    #- git clone https://token:$modelicaTests_token@gitlab.pam-retd.fr/thermosysproandco/modelicatests.git
    - git clone https://token:$modelicaTests_mirror_token@gitlab.pleiade.edf.fr/Phy13Models/pythontools/modelicatests_mirror.git
    - cd modelicatests*
    - pip install .
    - cd tests
    - cp ../../.test/*.json ./
    - dir
    - python3 run_cli.py config_ref.json config_new.json --ncpus 10 --timeout 60
  rules:
    - if: $CI_PROJECT_NAME == "ThermoSysPro_mirror"
  artifacts:
    when: always
    reports:
      junit: modelicatests*/tests/*-junit.xml
      annotations: modelicatests*/tests/annotations.json
    paths:
      - modelicatests*/tests/*.csv
      - modelicatests*/tests/*.html
      - modelicatests*/tests/*-junit.xml
      - modelicatests*/tests/annotations.json
